// Copyright (c) 2017 Cranium Software

#ifndef VS_PROJECT_TYPE_DATA_H
#define VS_PROJECT_TYPE_DATA_H

namespace CP2
{

static const char* const kaszVSProjectData[] =
{
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<Project ToolsVersion=\"4.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n"
	"  <PropertyGroup>\r\n"
	"    <MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>\r\n"
	"    <VisualStudioVersion Condition=\"'$(VisualStudioVersion)' == ''\">15.0</VisualStudioVersion>\r\n"
	"    <VSToolsPath Condition=\"'$(VSToolsPath)' == ''\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>\r\n"
	"    <NuGetPackageImportStamp>\r\n"
	"    </NuGetPackageImportStamp>\r\n"
	"  </PropertyGroup>\r\n"
	"  <Import Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists('$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props')\" />\r\n"
	"  <PropertyGroup>\r\n"
	"    <Configuration Condition=\" '$(Configuration)' == '' \">Debug</Configuration>\r\n"
	"    <Platform Condition=\" '$(Platform)' == '' \">AnyCPU</Platform>\r\n"
	"    <ProductVersion>8.0.30703</ProductVersion>\r\n"
	"    <SchemaVersion>2.0</SchemaVersion>\r\n"
	"    <ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>\r\n"
	"    <ProjectGuid>{",
	// project guid
	"}</ProjectGuid>\r\n"
	"    <OutputType>Library</OutputType>\r\n"
	"    <AppDesignerFolder>Properties</AppDesignerFolder>\r\n"
	"    <RootNamespace>",
	// language name
	"</RootNamespace>\r\n"
	"    <AssemblyName>",
	// language name
	"</AssemblyName>\r\n"
	"    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>\r\n"
	"    <FileAlignment>512</FileAlignment>\r\n"
	"    <SignAssembly>true</SignAssembly>\r\n"
	"    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>\r\n"
	"    <StartAction>Program</StartAction>\r\n"
	"    <StartProgram>$(DevEnvDir)devenv.exe</StartProgram>\r\n"
	"    <StartArguments>/rootSuffix Exp</StartArguments>\r\n"
	"  </PropertyGroup>\r\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">\r\n"
	"    <DebugSymbols>true</DebugSymbols>\r\n"
	"    <DebugType>full</DebugType>\r\n"
	"    <Optimize>false</Optimize>\r\n"
	"    <OutputPath>bin\\Debug\\</OutputPath>\r\n"
	"    <DefineConstants>DEBUG;TRACE</DefineConstants>\r\n"
	"    <ErrorReport>prompt</ErrorReport>\r\n"
	"    <WarningLevel>4</WarningLevel>\r\n"
	"  </PropertyGroup>\r\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">\r\n"
	"    <DebugType>pdbonly</DebugType>\r\n"
	"    <Optimize>true</Optimize>\r\n"
	"    <OutputPath>bin\\Release\\</OutputPath>\r\n"
	"    <DefineConstants>TRACE</DefineConstants>\r\n"
	"    <ErrorReport>prompt</ErrorReport>\r\n"
	"    <WarningLevel>4</WarningLevel>\r\n"
	"  </PropertyGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Reference Include=\"EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"envdte100, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"envdte90, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build.Framework\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Framework.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build.Utilities.Core\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Utilities.Core.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.CSharp\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ComponentModelHost\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition.Configuration, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.Configuration.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Designer.Interfaces, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.OLE.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.Interop, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.Interop.dll</HintPath>\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.VS, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.VS.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.8.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.9.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.10.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.11.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.1.DesignTime\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <SpecificVersion>True</SpecificVersion>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.15.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.TextManager.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Threading.15.0.240\\lib\\net45\\Microsoft.VisualStudio.Threading.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Validation.15.0.82\\lib\\net45\\Microsoft.VisualStudio.Validation.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"PresentationCore\" />\r\n"
	"    <Reference Include=\"PresentationFramework\" />\r\n"
	"    <Reference Include=\"System\" />\r\n"
	"    <Reference Include=\"System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\System.Collections.Immutable.1.3.1\\lib\\portable-net45+win8+wp8+wpa81\\System.Collections.Immutable.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.ComponentModel.Composition\" />\r\n"
	"    <Reference Include=\"System.Composition.AttributedModel, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.AttributedModel.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Convention, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Convention.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Hosting, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Hosting.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Runtime, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Runtime.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.TypedParts, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.TypedParts.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Core\" />\r\n"
	"    <Reference Include=\"System.Data\" />\r\n"
	"    <Reference Include=\"System.Design\" />\r\n"
	"    <Reference Include=\"System.Drawing\" />\r\n"
	"    <Reference Include=\"System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Tpl.Dataflow.4.5.24\\lib\\portable-net45+win8+wpa81\\System.Threading.Tasks.Dataflow.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Windows.Forms\" />\r\n"
	"    <Reference Include=\"System.Xaml\" />\r\n"
	"    <Reference Include=\"System.Xml\" />\r\n"
	"    <Reference Include=\"System.Xml.Linq\" />\r\n"
	"    <Reference Include=\"VSLangProj, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"WindowsBase\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <ProjectReference Include=\"..\\ProjectTemplate\\",
	// language name
	".ProjectTemplate.csproj\">\r\n"
	"      <Project>{",
	// project template project guid
	"}</Project>\r\n"
	"      <Name>",
	// language name
	".ProjectTemplate</Name>\r\n"
	"      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>\r\n"
	"      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>\r\n"
	"      <VSIXSubPath>ProjectTemplates</VSIXSubPath>\r\n"
	"    </ProjectReference>\r\n"
	"  </ItemGroup>\r\n"
	"  <!-- \r\n"
	"  Resources for our new project system\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <EmbeddedResource Include=\"Resources.resx\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </EmbeddedResource>\r\n"
	"    <EmbeddedResource Include=\"VSPackage.resx\">\r\n"
	"      <MergeWithCTO>true</MergeWithCTO>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </EmbeddedResource>\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Compile Include=\"MyConfiguredProject.cs\" />\r\n"
	"    <Compile Include=\"MyUnconfiguredProject.cs\" />\r\n"
	"    <Compile Include=\"ProjectProperties.cs\" />\r\n"
	"    <Compile Include=\"SourceDebuggerLaunchProvider.cs\" />\r\n"
	"    <Compile Include=\"VsPackage.cs\" />\r\n"
	"    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"app.config\" />\r\n"
	"    <None Include=\"packages.config\" />\r\n"
	"    <None Include=\"source.extension.vsixmanifest\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <None Include=\"Key.snk\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <!-- \r\n"
	"  These are the parts of the custom project system which will be deployed as part of the \r\n"
	"  final implementation, and provide the basic processing for handling rules in CPS.\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".props\" />\r\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".targets\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <!--\r\n"
	"  The XAML files provide both compile-time implementations for CPS rules as well as\r\n"
	"  runtime information for property pages.  They will also be deployed as part of the\r\n"
	"  final package.\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"BuildSystem\\Rules\\ProjectItemsSchema.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <None Include=\"BuildSystem\\Rules\\source.browseobject.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general_file.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\folder.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\none.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\scc.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\debugger_general.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\source.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.browseobject.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\SourceDebugger.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.Analyzers.15.0.743\\analyzers\\Microsoft.VisualStudio.ProjectSystem.Analyzers.dll\" />\r\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.Threading.Analyzers.15.0.240\\analyzers\\cs\\Microsoft.VisualStudio.Threading.Analyzers.dll\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" />\r\n"
	"  <Import Project=\"$(VSToolsPath)\\VSSDK\\Microsoft.VsSDK.targets\" Condition=\"'$(VSToolsPath)' != ''\" />\r\n"
	"  <!-- TODO: This copies the build authoring to a well-known location so that on the machine this project builds on,\r\n"
	"       the projects created by the 3rd party consumer can open and build. But the real 3rd party consumer will not\r\n"
	"       have run this step so they won't be able to open their projects. \r\n"
	"       To ship, the project type author must create an MSI that places these files in a well-known location on the\r\n"
	"       customer machine and update the project template to point at that location.-->\r\n"
	"  <Target Name=\"AfterBuild\">\r\n"
	"    <ItemGroup>\r\n"
	"      <BuildSystemToCopy Include=\"BuildSystem\\DeployedBuildSystem\\**\\*\" />\r\n"
	"      <RulesToCopy Include=\"BuildSystem\\Rules\\**\\*\" />\r\n"
	"    </ItemGroup>\r\n"
	"    <Copy SourceFiles=\"@(BuildSystemToCopy)\" DestinationFiles=\"@(BuildSystemToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\r\n"
	"    <Copy SourceFiles=\"@(RulesToCopy)\" DestinationFiles=\"@(RulesToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\Rules\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\r\n"
	"  </Target>\r\n"
	"  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">\r\n"
	"    <PropertyGroup>\r\n"
	"      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>\r\n"
	"    </PropertyGroup>\r\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets'))\" />\r\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets'))\" />\r\n"
	"  </Target>\r\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" />\r\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" />\r\n"
	"</Project>"
};

static const char* const kszVSProjectPropertiesCS =
	//"namespace WindowsScript\r\n"
	"{\r\n"
	"    using System;\r\n"
	"    using System.Collections.Generic;\r\n"
	"    using System.ComponentModel.Composition;\r\n"
	"    using System.Linq;\r\n"
	"    using System.Text;\r\n"
	"    using System.Threading.Tasks;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem.Properties;\r\n"
	"\r\n"
	"    [Export]\r\n"
	"    internal partial class ProjectProperties : StronglyTypedPropertyAccess\r\n"
	"    {\r\n"
	"        /// <summary>\r\n"
	"        /// Initializes a new instance of the <see cref=\"ProjectProperties\"/> class.\r\n"
	"        /// </summary>\r\n"
	"        [ImportingConstructor]\r\n"
	"        public ProjectProperties(ConfiguredProject configuredProject)\r\n"
	"            : base(configuredProject)\r\n"
	"        {\r\n"
	"        }\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// Initializes a new instance of the <see cref=\"ProjectProperties\"/> class.\r\n"
	"        /// </summary>\r\n"
	"        public ProjectProperties(ConfiguredProject configuredProject, string file, string itemType, string itemName)\r\n"
	"            : base(configuredProject, file, itemType, itemName)\r\n"
	"        {\r\n"
	"        }\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// Initializes a new instance of the <see cref=\"ProjectProperties\"/> class.\r\n"
	"        /// </summary>\r\n"
	"        public ProjectProperties(ConfiguredProject configuredProject, IProjectPropertiesContext projectPropertiesContext)\r\n"
	"            : base(configuredProject, projectPropertiesContext)\r\n"
	"        {\r\n"
	"        }\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// Initializes a new instance of the <see cref=\"ProjectProperties\"/> class.\r\n"
	"        /// </summary>\r\n"
	"        public ProjectProperties(ConfiguredProject configuredProject, UnconfiguredProject unconfiguredProject)\r\n"
	"            : base(configuredProject, unconfiguredProject)\r\n"
	"        {\r\n"
	"        }\r\n"
	"    }\r\n"
	"}\r\n";

static const char* kaszVSUnconfiguredProjectCS[] =
{
	"{\r\n"
	"    using System;\r\n"
	"    using System.ComponentModel.Composition;\r\n"
	"    using System.Diagnostics.CodeAnalysis;\r\n"
	"    using System.Threading.Tasks;\r\n"
	"    using System.Threading.Tasks.Dataflow;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem.VS;\r\n"
	"    using Microsoft.VisualStudio.Shell;\r\n"
	"    using Microsoft.VisualStudio.Shell.Interop;\r\n"
	"    using Task = System.Threading.Tasks.Task;\r\n"
	"\r\n"
	"    [Export]\r\n"
	"    [AppliesTo(MyUnconfiguredProject.UniqueCapability)]\r\n"
	"    [ProjectTypeRegistration(VsPackage.ProjectTypeGuid, \"",
	// language name
	"\", \"#2\", ProjectExtension, Language, resourcePackageGuid: VsPackage.PackageGuid, PossibleProjectExtensions = ProjectExtension, ProjectTemplatesDir = @\"..\\..\\Templates\\Projects\\MyCustomProject\")]\r\n"
	"    [ProvideProjectItem(VsPackage.ProjectTypeGuid, \"My Items\", @\"..\\..\\Templates\\ProjectItems\\MyCustomProject\", 500)]\r\n"
	"    internal class MyUnconfiguredProject\r\n"
	"    {\r\n"
	"        /// <summary>\r\n"
	"        /// The file extension used by your project type.\r\n"
	"        /// This does not include the leading period.\r\n"
	"        /// </summary>\r\n"
	"        internal const string ProjectExtension = \"",
	// short name
	"proj\";\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// A project capability that is present in your project type and none others.\r\n"
	"        /// This is a convenient constant that may be used by your extensions so they\r\n"
	"        /// only apply to instances of your project type.\r\n"
	"        /// </summary>\r\n"
	"        /// <remarks>\r\n"
	"        /// This value should be kept in sync with the capability as actually defined in your .targets.\r\n"
	"        /// </remarks>\r\n"
	"        internal const string UniqueCapability = \"",
	// language name
	"Capability\";\r\n"
	"\r\n"
	"        internal const string Language = \"",
	// language name
	"\";\r\n"
	"\r\n"
	"        [ImportingConstructor]\r\n"
	"        public MyUnconfiguredProject(UnconfiguredProject unconfiguredProject)\r\n"
	"        {\r\n"
	"            this.ProjectHierarchies = new OrderPrecedenceImportCollection<IVsHierarchy>(projectCapabilityCheckProvider: unconfiguredProject);\r\n"
	"        }\r\n"
	"\r\n"
	"        [Import]\r\n"
	"        internal UnconfiguredProject UnconfiguredProject { get; private set; }\r\n"
	"\r\n"
	"        [Import]\r\n"
	"        internal IActiveConfiguredProjectSubscriptionService SubscriptionService { get; private set; }\r\n"
	"\r\n"
	"        [Import]\r\n"
	"        internal IProjectThreadingService ProjectThreadingService { get; private set; }\r\n"
	"\r\n"
	"        [Import]\r\n"
	"        internal ActiveConfiguredProject<ConfiguredProject> ActiveConfiguredProject { get; private set; }\r\n"
	"\r\n"
	"        [Import]\r\n"
	"        internal ActiveConfiguredProject<MyConfiguredProject> MyActiveConfiguredProject { get; private set; }\r\n"
	"\r\n"
	"        [ImportMany(ExportContractNames.VsTypes.IVsProject, typeof(IVsProject))]\r\n"
	"        internal OrderPrecedenceImportCollection<IVsHierarchy> ProjectHierarchies { get; private set; }\r\n"
	"\r\n"
	"        internal IVsHierarchy ProjectHierarchy\r\n"
	"        {\r\n"
	"            get { return this.ProjectHierarchies.Single().Value; }\r\n"
	"        }\r\n"
	"    }\r\n"
	"}\r\n"
};

static const char* const kszVSConfiguredProjectCS =
	"{\r\n"
	"    using System;\r\n"
	"    using System.ComponentModel.Composition;\r\n"
	"    using System.Diagnostics.CodeAnalysis;\r\n"
	"    using System.Threading.Tasks;\r\n"
	"    using System.Threading.Tasks.Dataflow;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem;\r\n"
	"    using Microsoft.VisualStudio.Shell;\r\n"
	"    using Microsoft.VisualStudio.Shell.Interop;\r\n"
	"    using Task = System.Threading.Tasks.Task;\r\n"
	"\r\n"
	"    [Export]\r\n"
	"    [AppliesTo(MyUnconfiguredProject.UniqueCapability)]\r\n"
	"    internal class MyConfiguredProject\r\n"
	"    {\r\n"
	"        [Import, SuppressMessage(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\", Justification = \"MEF\")]\r\n"
	"        internal ConfiguredProject ConfiguredProject { get; private set; }\r\n"
	"\r\n"
	"        [Import, SuppressMessage(\"Microsoft.Performance\", \"CA1811:AvoidUncalledPrivateCode\", Justification = \"MEF\")]\r\n"
	"        internal ProjectProperties Properties { get; private set; }\r\n"
	"    }\r\n"
	"}\r\n";

static const char* const kszResourcesResX =
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<root>\r\n"
	"  <!-- \r\n"
	"    Microsoft ResX Schema \r\n"
	"    \r\n"
	"    Version 2.0\r\n"
	"    \r\n"
	"    The primary goals of this format is to allow a simple XML format \r\n"
	"    that is mostly human readable. The generation and parsing of the \r\n"
	"    various data types are done through the TypeConverter classes \r\n"
	"    associated with the data types.\r\n"
	"    \r\n"
	"    Example:\r\n"
	"    \r\n"
	"    ... ado.net/XML headers & schema ...\r\n"
	"    <resheader name=\"resmimetype\">text/microsoft-resx</resheader>\r\n"
	"    <resheader name=\"version\">2.0</resheader>\r\n"
	"    <resheader name=\"reader\">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>\r\n"
	"    <resheader name=\"writer\">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>\r\n"
	"    <data name=\"Name1\"><value>this is my long string</value><comment>this is a comment</comment></data>\r\n"
	"    <data name=\"Color1\" type=\"System.Drawing.Color, System.Drawing\">Blue</data>\r\n"
	"    <data name=\"Bitmap1\" mimetype=\"application/x-microsoft.net.object.binary.base64\">\r\n"
	"        <value>[base64 mime encoded serialized .NET Framework object]</value>\r\n"
	"    </data>\r\n"
	"    <data name=\"Icon1\" type=\"System.Drawing.Icon, System.Drawing\" mimetype=\"application/x-microsoft.net.object.bytearray.base64\">\r\n"
	"        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>\r\n"
	"        <comment>This is a comment</comment>\r\n"
	"    </data>\r\n"
	"                \r\n"
	"    There are any number of \"resheader\" rows that contain simple \r\n"
	"    name/value pairs.\r\n"
	"    \r\n"
	"    Each data row contains a name, and value. The row also contains a \r\n"
	"    type or mimetype. Type corresponds to a .NET class that support \r\n"
	"    text/value conversion through the TypeConverter architecture. \r\n"
	"    Classes that don't support this are serialized and stored with the \r\n"
	"    mimetype set.\r\n"
	"    \r\n"
	"    The mimetype is used for serialized objects, and tells the \r\n"
	"    ResXResourceReader how to depersist the object. This is currently not \r\n"
	"    extensible. For a given mimetype the value must be set accordingly:\r\n"
	"    \r\n"
	"    Note - application/x-microsoft.net.object.binary.base64 is the format \r\n"
	"    that the ResXResourceWriter will generate, however the reader can \r\n"
	"    read any of the formats listed below.\r\n"
	"    \r\n"
	"    mimetype: application/x-microsoft.net.object.binary.base64\r\n"
	"    value   : The object must be serialized with \r\n"
	"            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"    \r\n"
	"    mimetype: application/x-microsoft.net.object.soap.base64\r\n"
	"    value   : The object must be serialized with \r\n"
	"            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"\r\n"
	"    mimetype: application/x-microsoft.net.object.bytearray.base64\r\n"
	"    value   : The object must be serialized into a byte array \r\n"
	"            : using a System.ComponentModel.TypeConverter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"    -->\r\n"
	"  <xsd:schema id=\"root\" xmlns=\"\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">\r\n"
	"    <xsd:import namespace=\"http://www.w3.org/XML/1998/namespace\" />\r\n"
	"    <xsd:element name=\"root\" msdata:IsDataSet=\"true\">\r\n"
	"      <xsd:complexType>\r\n"
	"        <xsd:choice maxOccurs=\"unbounded\">\r\n"
	"          <xsd:element name=\"metadata\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" use=\"required\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"type\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute ref=\"xml:space\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"assembly\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:attribute name=\"alias\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"data\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n"
	"                <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"2\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" msdata:Ordinal=\"1\" />\r\n"
	"              <xsd:attribute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />\r\n"
	"              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />\r\n"
	"              <xsd:attribute ref=\"xml:space\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"resheader\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"        </xsd:choice>\r\n"
	"      </xsd:complexType>\r\n"
	"    </xsd:element>\r\n"
	"  </xsd:schema>\r\n"
	"  <resheader name=\"resmimetype\">\r\n"
	"    <value>text/microsoft-resx</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"version\">\r\n"
	"    <value>2.0</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"reader\">\r\n"
	"    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"writer\">\r\n"
	"    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r\n"
	"  </resheader>\r\n"
	"  <data name=\"Application\" xml:space=\"preserve\">\r\n"
	"    <value>Application</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ApplicationIcon\" xml:space=\"preserve\">\r\n"
	"    <value>Application Icon</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ApplicationIconDescription\" xml:space=\"preserve\">\r\n"
	"    <value>Sets the .ico file to use as your application icon.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"AssemblyName\" xml:space=\"preserve\">\r\n"
	"    <value>Assembly Name</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"AssemblyNameDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The name of the output file that will hold assembly metadata.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"DefaultNamespace\" xml:space=\"preserve\">\r\n"
	"    <value>Default Namespace</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"DefaultNamespaceDescription\" xml:space=\"preserve\">\r\n"
	"    <value>Specifies the default namespace for added items, such as classes, that are added via the Add New Item Dialog Box.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"GeneralCaption\" xml:space=\"preserve\">\r\n"
	"    <value>General</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"OutputFile\" xml:space=\"preserve\">\r\n"
	"    <value>Output File</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"OutputFileDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The name of the project's primary output file.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"OutputType\" xml:space=\"preserve\">\r\n"
	"    <value>Output Type</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"OutputTypeDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The type of application to build.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"Project\" xml:space=\"preserve\">\r\n"
	"    <value>Project</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ProjectFile\" xml:space=\"preserve\">\r\n"
	"    <value>Project File</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ProjectFileDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The name of the file containing build, configuration, and other information about the project.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ProjectFolder\" xml:space=\"preserve\">\r\n"
	"    <value>Project Folder</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"ProjectFolderDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The absolute location of the project.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"StartupObject\" xml:space=\"preserve\">\r\n"
	"    <value>Startup Object</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"StartupObjectDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The name of the class that contains the static Main method that you want called when you launch your application.</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"TargetFrameworkMoniker\" xml:space=\"preserve\">\r\n"
	"    <value>Target Framework Moniker</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"TargetFrameworkMonikerDescription\" xml:space=\"preserve\">\r\n"
	"    <value>The version of the Common Language Runtime to use for output assembly.</value>\r\n"
	"  </data>\r\n"
	"</root>";

static const char* kaszVSPackageResXData[] =
{
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<root>\r\n"
	"  <!-- \r\n"
	"    Microsoft ResX Schema \r\n"
	"    \r\n"
	"    Version 2.0\r\n"
	"    \r\n"
	"    The primary goals of this format is to allow a simple XML format \r\n"
	"    that is mostly human readable. The generation and parsing of the \r\n"
	"    various data types are done through the TypeConverter classes \r\n"
	"    associated with the data types.\r\n"
	"    \r\n"
	"    Example:\r\n"
	"    \r\n"
	"    ... ado.net/XML headers & schema ...\r\n"
	"    <resheader name=\"resmimetype\">text/microsoft-resx</resheader>\r\n"
	"    <resheader name=\"version\">2.0</resheader>\r\n"
	"    <resheader name=\"reader\">System.Resources.ResXResourceReader, System.Windows.Forms, ...</resheader>\r\n"
	"    <resheader name=\"writer\">System.Resources.ResXResourceWriter, System.Windows.Forms, ...</resheader>\r\n"
	"    <data name=\"Name1\"><value>this is my long string</value><comment>this is a comment</comment></data>\r\n"
	"    <data name=\"Color1\" type=\"System.Drawing.Color, System.Drawing\">Blue</data>\r\n"
	"    <data name=\"Bitmap1\" mimetype=\"application/x-microsoft.net.object.binary.base64\">\r\n"
	"        <value>[base64 mime encoded serialized .NET Framework object]</value>\r\n"
	"    </data>\r\n"
	"    <data name=\"Icon1\" type=\"System.Drawing.Icon, System.Drawing\" mimetype=\"application/x-microsoft.net.object.bytearray.base64\">\r\n"
	"        <value>[base64 mime encoded string representing a byte array form of the .NET Framework object]</value>\r\n"
	"        <comment>This is a comment</comment>\r\n"
	"    </data>\r\n"
	"                \r\n"
	"    There are any number of \"resheader\" rows that contain simple \r\n"
	"    name/value pairs.\r\n"
	"    \r\n"
	"    Each data row contains a name, and value. The row also contains a \r\n"
	"    type or mimetype. Type corresponds to a .NET class that support \r\n"
	"    text/value conversion through the TypeConverter architecture. \r\n"
	"    Classes that don't support this are serialized and stored with the \r\n"
	"    mimetype set.\r\n"
	"    \r\n"
	"    The mimetype is used for serialized objects, and tells the \r\n"
	"    ResXResourceReader how to depersist the object. This is currently not \r\n"
	"    extensible. For a given mimetype the value must be set accordingly:\r\n"
	"    \r\n"
	"    Note - application/x-microsoft.net.object.binary.base64 is the format \r\n"
	"    that the ResXResourceWriter will generate, however the reader can \r\n"
	"    read any of the formats listed below.\r\n"
	"    \r\n"
	"    mimetype: application/x-microsoft.net.object.binary.base64\r\n"
	"    value   : The object must be serialized with \r\n"
	"            : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"    \r\n"
	"    mimetype: application/x-microsoft.net.object.soap.base64\r\n"
	"    value   : The object must be serialized with \r\n"
	"            : System.Runtime.Serialization.Formatters.Soap.SoapFormatter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"\r\n"
	"    mimetype: application/x-microsoft.net.object.bytearray.base64\r\n"
	"    value   : The object must be serialized into a byte array \r\n"
	"            : using a System.ComponentModel.TypeConverter\r\n"
	"            : and then encoded with base64 encoding.\r\n"
	"    -->\r\n"
	"  <xsd:schema id=\"root\" xmlns=\"\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:msdata=\"urn:schemas-microsoft-com:xml-msdata\">\r\n"
	"    <xsd:import namespace=\"http://www.w3.org/XML/1998/namespace\" />\r\n"
	"    <xsd:element name=\"root\" msdata:IsDataSet=\"true\">\r\n"
	"      <xsd:complexType>\r\n"
	"        <xsd:choice maxOccurs=\"unbounded\">\r\n"
	"          <xsd:element name=\"metadata\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" use=\"required\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"type\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute ref=\"xml:space\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"assembly\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:attribute name=\"alias\" type=\"xsd:string\" />\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"data\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n"
	"                <xsd:element name=\"comment\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"2\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" msdata:Ordinal=\"1\" />\r\n"
	"              <xsd:attribute name=\"type\" type=\"xsd:string\" msdata:Ordinal=\"3\" />\r\n"
	"              <xsd:attribute name=\"mimetype\" type=\"xsd:string\" msdata:Ordinal=\"4\" />\r\n"
	"              <xsd:attribute ref=\"xml:space\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"          <xsd:element name=\"resheader\">\r\n"
	"            <xsd:complexType>\r\n"
	"              <xsd:sequence>\r\n"
	"                <xsd:element name=\"value\" type=\"xsd:string\" minOccurs=\"0\" msdata:Ordinal=\"1\" />\r\n"
	"              </xsd:sequence>\r\n"
	"              <xsd:attribute name=\"name\" type=\"xsd:string\" use=\"required\" />\r\n"
	"            </xsd:complexType>\r\n"
	"          </xsd:element>\r\n"
	"        </xsd:choice>\r\n"
	"      </xsd:complexType>\r\n"
	"    </xsd:element>\r\n"
	"  </xsd:schema>\r\n"
	"  <resheader name=\"resmimetype\">\r\n"
	"    <value>text/microsoft-resx</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"version\">\r\n"
	"    <value>2.0</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"reader\">\r\n"
	"    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r\n"
	"  </resheader>\r\n"
	"  <resheader name=\"writer\">\r\n"
	"    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>\r\n"
	"  </resheader>\r\n"
	"  <data name=\"1\" xml:space=\"preserve\">\r\n"
	"    <value>",
	// langauge name
	"</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"2\" xml:space=\"preserve\">\r\n"
	"    <value>",
	// langauge name
	" Project Files (*.",
	// short name
	"proj);*.",
	// short name
	"proj</value>\r\n"
	"  </data>\r\n"
	"  <data name=\"3\" xml:space=\"preserve\">\r\n"
	"    <value>",
	// langauge name
	" Items</value>\r\n"
	"  </data>\r\n"
	"</root>"
};

static const char* kaszVSPackageCSData[] =
{
	"{\r\n"
	"    using System;\r\n"
	"    using System.ComponentModel;\r\n"
	"    using System.Runtime.InteropServices;\r\n"
	"    using Microsoft.VisualStudio.Shell;\r\n"
	"\r\n"
	"    /// <summary>\r\n"
	"    /// This class implements the package exposed by this assembly.\r\n"
	"    /// </summary>\r\n"
	"    /// <remarks>\r\n"
	"    /// This package is required if you want to define adds custom commands (ctmenu)\r\n"
	"    /// or localized resources for the strings that appear in the New Project and Open Project dialogs.\r\n"
	"    /// Creating project extensions or project types does not actually require a VSPackage.\r\n"
	"    /// </remarks>\r\n"
	"    [PackageRegistration(UseManagedResourcesOnly = true)]\r\n"
	"    [Description(\"A custom project type based on CPS\")]\r\n"
	"    [Guid(VsPackage.PackageGuid)]\r\n"
	"    public sealed class VsPackage : Package\r\n"
	"    {\r\n"
	"        /// <summary>\r\n"
	"        /// The GUID for this package.\r\n"
	"        /// </summary>\r\n"
	"        public const string PackageGuid = \"",
	// package guid
	"\";\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// The GUID for this project type.  It is unique with the project file extension and\r\n"
	"        /// appears under the VS registry hive's Projects key.\r\n"
	"        /// </summary>\r\n"
	"        public const string ProjectTypeGuid = \"",
	// project type guid
	"\";\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// The file extension of this project type.  No preceding period.\r\n"
	"        /// </summary>\r\n"
	"        public const string ProjectExtension = \"",
	// short name
	"proj\";\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// The default namespace this project compiles with, so that manifest\r\n"
	"        /// resource names can be calculated for embedded resources.\r\n"
	"        /// </summary>\r\n"
	"        internal const string DefaultNamespace = \"",
	// language name
	"\";\r\n"
	"    }\r\n"
	"}\r\n"
};

static const char* kaszVSPackageManifestData[] =
{
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<PackageManifest Version=\"2.0.0\" xmlns=\"http://schemas.microsoft.com/developer/vsx-schema/2011\" xmlns:d=\"http://schemas.microsoft.com/developer/vsx-schema-design/2011\">\r\n"
	"  <Metadata>\r\n"
	"    <Identity Id=\"",
	// language name
	".ProjectType..61d255dd-a819-4936-9f07-e660d0572111\" Version=\"1.0\" Language=\"en-US\" Publisher=\"",
	// language name
	".ProjectType\" />\r\n"
	"    <DisplayName>",
	// language name
	" VSIX</DisplayName>\r\n"
	"    <Description xml:space=\"preserve\">A template for creating a ",
	// language name
	" project.</Description>\r\n"
	"  </Metadata>\r\n"
	"  <Installation>\r\n"
	"    <InstallationTarget Id=\"Microsoft.VisualStudio.Pro\" Version=\"15.0\" />\r\n"
	"  </Installation>\r\n"
	"  <Dependencies>\r\n"
	"    <!--<Dependency Id=\"Microsoft.Framework.NDP\" DisplayName=\"Microsoft .NET Framework\" d:Source=\"Manual\" Version=\"4.6\" />-->\r\n"
	"    <!--<Dependency d:Source=\"Installed\" Id=\"B73A99D8-FCAA-4197-9122-F8ABA095A72F\" DisplayName=\"Visual Studio Common Project System v14\" Version=\"[11.2,14.0)\" />-->\r\n"
	"  </Dependencies>\r\n"
	"  <Assets>\r\n"
	"    <Asset Type=\"Microsoft.VisualStudio.MefComponent\" d:Source=\"Project\" d:ProjectName=\"",
	// language name
	".ProjectType\" Path=\"|",
	// language name
	".ProjectType|\"/>\r\n"
	"    <Asset Type=\"Microsoft.VisualStudio.VsPackage\" d:Source=\"Project\" d:ProjectName=\"",
	// language name
	".ProjectType\" Path=\"|",
	// language name
	".ProjectType;PkgdefProjectOutputGroup|\" />\r\n"
	"    <Asset Type=\"Microsoft.VisualStudio.ProjectTemplate\" d:Source=\"Project\" d:ProjectName=\"",
	// language name
	".ProjectTemplate\" d:TargetPath=\"|",
	// language name
	".ProjectTemplate;TemplateProjectOutputGroup|\" Path=\"ProjectTemplates\" d:VsixSubPath=\"ProjectTemplates\" />\r\n"
	"  </Assets>\r\n"
	"  <Prerequisites>\r\n"
	"    <Prerequisite Id=\"Microsoft.VisualStudio.Component.CoreEditor\" Version=\"[15.0,16.0)\" DisplayName=\"Visual Studio core editor\" />\r\n"
	"  </Prerequisites>\r\n"
};

static const char* kaszVSAssemblyInfoCSData[] =
{
	"using System.Reflection;\n"
	"using System.Runtime.CompilerServices;\n"
	"using System.Runtime.InteropServices;\n"
	"\n"
	"[assembly: Microsoft.VisualStudio.Shell.ProvideCodeBase(CodeBase = @\"$PackageFolder$\\"
	// language name
	,".dll\")]\n"
	"\n"
	"// General Information about an assembly is controlled through the following \n"
	"// set of attributes. Change these attribute values to modify the information\n"
	"// associated with an assembly.\n"
	"[assembly: AssemblyTitle(\""
	// language name
	,".ProjectType\")]\n"
	"[assembly: AssemblyDescription(\"\")]\n"
	"[assembly: AssemblyConfiguration(\"\")]\n"
	"[assembly: AssemblyCompany(\"\")]\n"
	"[assembly: AssemblyProduct(\""
	// language name
	,".ProjectType\")]\n"
	"[assembly: AssemblyCopyright(\"Copyright © ??? 2017\")]\n"
	"[assembly: AssemblyTrademark(\"\")]\n"
	"[assembly: AssemblyCulture(\"\")]\n"
	"\n"
	"// Setting ComVisible to false makes the types in this assembly not visible \n"
	"// to COM components.  If you need to access a type in this assembly from \n"
	"// COM, set the ComVisible attribute to true on that type.\n"
	"[assembly: ComVisible(false)]\n"
	"\n"
	"// The following GUID is for the ID of the typelib if this project is exposed to COM\n"
	"[assembly: Guid(\"c7d7fd14-2c44-4ec2-975b-18e8b1bbadd9\")]\n"
	"\n"
	"// Version information for an assembly consists of the following four values:\n"
	"//\n"
	"//      Major Version\n"
	"//      Minor Version \n"
	"//      Build Number\n"
	"//      Revision\n"
	"//\n"
	"// You can specify all the values or you can default the Build and Revision Numbers \n"
	"// by using the '*' as shown below:\n"
	"[assembly: AssemblyVersion(\"0.1.*\")]\n"
	"[assembly: AssemblyFileVersion(\"0.1.0.0\")]\n"
};

static const char* kaszDebuggerSourceCS[] =
{
	"\r\n{\r\n"
	"    using System;\r\n"
	"    using System.Collections.Generic;\r\n"
	"    using System.ComponentModel.Composition;\r\n"
	"    using System.IO;\r\n"
	"    using System.Threading.Tasks;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem.Debug;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem.Properties;\r\n"
	"    using Microsoft.VisualStudio.ProjectSystem.VS.Debug;\r\n"
	"\r\n"
	"    [ExportDebugger(SourceDebugger.SchemaName)]\r\n"
	"    [AppliesTo(MyUnconfiguredProject.UniqueCapability)]\r\n"
	"    public class SourceDebuggerLaunchProvider : DebugLaunchProviderBase\r\n"
	"    {\r\n"
	"        [ImportingConstructor]\r\n"
	"        public SourceDebuggerLaunchProvider(ConfiguredProject configuredProject)\r\n"
	"            : base(configuredProject)\r\n"
	"        {\r\n"
	"        }\r\n"
	"\r\n"
	"        [ExportPropertyXamlRuleDefinition(\"",
	// language name
	", Version=1.0.0.0, Culture=neutral, PublicKeyToken=9be6e469bc4921f1\", \"XamlRuleToCode:SourceDebuggerLaunchProviderDebugger.xaml\", \"Project\")]\r\n"
	"        [AppliesTo(MyUnconfiguredProject.UniqueCapability)]\r\n"
	"        private object DebuggerXaml { get { throw new NotImplementedException(); } }\r\n"
	"\r\n"
	"        /// <summary>\r\n"
	"        /// Gets project properties that the debugger needs to launch.\r\n"
	"        /// </summary>\r\n"
	"        [Import]\r\n"
	"        private ProjectProperties ProjectProperties { get; set; }\r\n"
	"\r\n"
	"        public override async Task<bool> CanLaunchAsync(DebugLaunchOptions launchOptions)\r\n"
	"        {\r\n"
	"            var generalProperties = await this.ProjectProperties.GetConfigurationGeneralPropertiesAsync();\r\n"
	"            string startupItem = await generalProperties.StartItem.GetEvaluatedValueAtEndAsync();\r\n"
	"            return !string.IsNullOrEmpty(startupItem);\r\n"
	"        }\r\n"
	"\r\n"
	"        public override async Task<IReadOnlyList<IDebugLaunchSettings>> QueryDebugTargetsAsync(DebugLaunchOptions launchOptions)\r\n"
	"        {\r\n"
	"            var settings = new DebugLaunchSettings(launchOptions);\r\n"
	"\r\n"
	"            // The properties that are available via DebuggerProperties are determined by the property XAML files in your project.\r\n"
	"            var debuggerProperties = await this.ProjectProperties.GetSourceDebuggerPropertiesAsync();\r\n"
	"            settings.CurrentDirectory = await debuggerProperties.RunWorkingDirectory.GetEvaluatedValueAtEndAsync();\r\n"
	"\r\n"
	"            string scriptCommand = await debuggerProperties.RunCommand.GetEvaluatedValueAtEndAsync();\r\n"
	"            string scriptArguments = await debuggerProperties.RunCommandArguments.GetEvaluatedValueAtEndAsync();\r\n"
	"\r\n"
	"            var generalProperties = await this.ProjectProperties.GetConfigurationGeneralPropertiesAsync();\r\n"
	"            string startupItem = await generalProperties.StartItem.GetEvaluatedValueAtEndAsync();\r\n"
	"\r\n"
	"            // SE - TODO: replace this stuff from the windows script example\r\n"
	"\r\n"
	"            if ((launchOptions & DebugLaunchOptions.NoDebug) == DebugLaunchOptions.NoDebug)\r\n"
	"            {\r\n"
	"                // No debug - launch cscript using cmd.exe to introduce a pause at the end\r\n"
	"                settings.Executable = Path.Combine(Environment.SystemDirectory, \"cmd.exe\");\r\n"
	"                settings.Arguments = string.Format(\"/c {0} \\\"{1}\\\" {2} & pause\", scriptCommand, startupItem, scriptArguments);\r\n"
	"            }\r\n"
	"            else\r\n"
	"            {\r\n"
	"                // Debug - launch cscript using the debugger switch //X\r\n"
	"                settings.Executable = scriptCommand;\r\n"
	"                settings.Arguments = string.Format(\"\\\"{0}\\\" //X {1}\", startupItem, scriptArguments);\r\n"
	"            }\r\n"
	"\r\n"
	"            settings.LaunchOperation = DebugLaunchOperation.CreateProcess;\r\n"
	"            settings.LaunchDebugEngineGuid = DebuggerEngines.ScriptEngine;\r\n"
	"\r\n"
	"            return new IDebugLaunchSettings[] { settings };\r\n"
	"        }\r\n"
	"    }\r\n"
	"}\r\n"
};

}

#endif
