#ifndef VS_PROJECT_TYPE_DATA_H
#define VS_PROJECT_TYPE_DATA_H

namespace CP2
{

static const char* const kaszVSProjectData[] =
{
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
	"<Project ToolsVersion=\"4.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\n"
	"  <PropertyGroup>\n"
	"    <MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>\n"
	"    <VisualStudioVersion Condition=\"'$(VisualStudioVersion)' == ''\">15.0</VisualStudioVersion>\n"
	"    <VSToolsPath Condition=\"'$(VSToolsPath)' == ''\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>\n"
	"    <NuGetPackageImportStamp>\n"
	"    </NuGetPackageImportStamp>\n"
	"  </PropertyGroup>\n"
	"  <Import Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists('$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props')\" />\n"
	"  <PropertyGroup>\n"
	"    <Configuration Condition=\" '$(Configuration)' == '' \">Debug</Configuration>\n"
	"    <Platform Condition=\" '$(Platform)' == '' \">AnyCPU</Platform>\n"
	"    <ProductVersion>8.0.30703</ProductVersion>\n"
	"    <SchemaVersion>2.0</SchemaVersion>\n"
	"    <ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>\n"
	"    <ProjectGuid>{",
	// project guid
	"}</ProjectGuid>\n"
	"    <OutputType>Library</OutputType>\n"
	"    <AppDesignerFolder>Properties</AppDesignerFolder>\n"
	"    <RootNamespace>",
	// language name
	"</RootNamespace>\n"
	"    <AssemblyName>",
	// language name
	"</AssemblyName>\n"
	"    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>\n"
	"    <FileAlignment>512</FileAlignment>\n"
	"    <SignAssembly>true</SignAssembly>\n"
	"    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>\n"
	"    <StartAction>Program</StartAction>\n"
	"    <StartProgram>$(DevEnvDir)devenv.exe</StartProgram>\n"
	"    <StartArguments>/rootSuffix Exp</StartArguments>\n"
	"  </PropertyGroup>\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">\n"
	"    <DebugSymbols>true</DebugSymbols>\n"
	"    <DebugType>full</DebugType>\n"
	"    <Optimize>false</Optimize>\n"
	"    <OutputPath>bin\\Debug\\</OutputPath>\n"
	"    <DefineConstants>DEBUG;TRACE</DefineConstants>\n"
	"    <ErrorReport>prompt</ErrorReport>\n"
	"    <WarningLevel>4</WarningLevel>\n"
	"  </PropertyGroup>\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">\n"
	"    <DebugType>pdbonly</DebugType>\n"
	"    <Optimize>true</Optimize>\n"
	"    <OutputPath>bin\\Release\\</OutputPath>\n"
	"    <DefineConstants>TRACE</DefineConstants>\n"
	"    <ErrorReport>prompt</ErrorReport>\n"
	"    <WarningLevel>4</WarningLevel>\n"
	"  </PropertyGroup>\n"
	"  <ItemGroup>\n"
	"    <Reference Include=\"EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\n"
	"    <Reference Include=\"envdte100, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"envdte90, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.Build\">\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.Build.Framework\">\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Framework.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.Build.Utilities.Core\">\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Utilities.Core.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.CSharp\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ComponentModelHost\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition.Configuration, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.Configuration.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Designer.Interfaces, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.OLE.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.Interop, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.Interop.dll</HintPath>\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.VS, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.VS.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.8.0\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.9.0\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.10.0\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.11.0\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.0\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.1.DesignTime\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime\">\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <SpecificVersion>True</SpecificVersion>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.15.0\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.TextManager.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Threading.15.0.240\\lib\\net45\\Microsoft.VisualStudio.Threading.dll</HintPath>\n"
	"      <Private>True</Private>\n"
	"    </Reference>\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Validation.15.0.82\\lib\\net45\\Microsoft.VisualStudio.Validation.dll</HintPath>\n"
	"      <Private>True</Private>\n"
	"    </Reference>\n"
	"    <Reference Include=\"PresentationCore\" />\n"
	"    <Reference Include=\"PresentationFramework\" />\n"
	"    <Reference Include=\"System\" />\n"
	"    <Reference Include=\"System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\System.Collections.Immutable.1.3.1\\lib\\portable-net45+win8+wp8+wpa81\\System.Collections.Immutable.dll</HintPath>\n"
	"      <Private>True</Private>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.ComponentModel.Composition\" />\n"
	"    <Reference Include=\"System.Composition.AttributedModel, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.AttributedModel.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Composition.Convention, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Convention.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Composition.Hosting, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Hosting.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Composition.Runtime, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Runtime.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Composition.TypedParts, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.TypedParts.dll</HintPath>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Core\" />\n"
	"    <Reference Include=\"System.Data\" />\n"
	"    <Reference Include=\"System.Design\" />\n"
	"    <Reference Include=\"System.Drawing\" />\n"
	"    <Reference Include=\"System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Tpl.Dataflow.4.5.24\\lib\\portable-net45+win8+wpa81\\System.Threading.Tasks.Dataflow.dll</HintPath>\n"
	"      <Private>True</Private>\n"
	"    </Reference>\n"
	"    <Reference Include=\"System.Windows.Forms\" />\n"
	"    <Reference Include=\"System.Xaml\" />\n"
	"    <Reference Include=\"System.Xml\" />\n"
	"    <Reference Include=\"System.Xml.Linq\" />\n"
	"    <Reference Include=\"VSLangProj, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\n"
	"    <Reference Include=\"WindowsBase\" />\n"
	"  </ItemGroup>\n"
	"  <ItemGroup>\n"
	"    <ProjectReference Include=\"..\\ProjectTemplate\\",
	// language name
	".ProjectTemplate.csproj\">\n"
	"      <Project>{",
	// project template project guid
	"}</Project>\n"
	"      <Name>",
	// language name
	".ProjectTemplate</Name>\n"
	"      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>\n"
	"      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>\n"
	"      <VSIXSubPath>ProjectTemplates</VSIXSubPath>\n"
	"    </ProjectReference>\n"
	"  </ItemGroup>\n"
	"  <!-- \n"
	"  Resources for our new project system\n"
	"  -->\n"
	"  <ItemGroup>\n"
	"    <EmbeddedResource Include=\"Resources.resx\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </EmbeddedResource>\n"
	"    <EmbeddedResource Include=\"VSPackage.resx\">\n"
	"      <MergeWithCTO>true</MergeWithCTO>\n"
	"      <SubType>Designer</SubType>\n"
	"    </EmbeddedResource>\n"
	"  </ItemGroup>\n"
	"  <ItemGroup>\n"
	"    <Compile Include=\"MyConfiguredProject.cs\" />\n"
	"    <Compile Include=\"MyUnconfiguredProject.cs\" />\n"
	"    <Compile Include=\"ProjectProperties.cs\" />\n"
	"    <Compile Include=\"ScriptDebuggerLaunchProvider.cs\" />\n"
	"    <Compile Include=\"VsPackage.cs\" />\n"
	"    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\n"
	"  </ItemGroup>\n"
	"  <ItemGroup>\n"
	"    <None Include=\"app.config\" />\n"
	"    <None Include=\"packages.config\" />\n"
	"    <None Include=\"source.extension.vsixmanifest\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </None>\n"
	"    <None Include=\"Key.snk\" />\n"
	"  </ItemGroup>\n"
	"  <!-- \n"
	"  These are the parts of the custom project system which will be deployed as part of the \n"
	"  final implementation, and provide the basic processing for handling rules in CPS.\n"
	"  -->\n"
	"  <ItemGroup>\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".props\" />\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".targets\" />\n"
	"  </ItemGroup>\n"
	"  <!--\n"
	"  The XAML files provide buth compile-time implementations for CPS rules as well as\n"
	"  runtime information for property pages.  They will also be deployed as part of the\n"
	"  final package.\n"
	"  -->\n"
	"  <ItemGroup>\n"
	"    <None Include=\"BuildSystem\\Rules\\ProjectItemsSchema.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </None>\n"
	"    <None Include=\"BuildSystem\\Rules\\script.browseobject.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </None>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general_file.xaml\">\n"
	"      <RuleInjection>None</RuleInjection>\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\folder.xaml\">\n"
	"      <RuleInjection>None</RuleInjection>\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\none.xaml\">\n"
	"      <RuleInjection>None</RuleInjection>\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\scc.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\debugger_general.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\script.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.browseobject.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\ScriptDebugger.xaml\">\n"
	"      <SubType>Designer</SubType>\n"
	"    </XamlPropertyRule>\n"
	"  </ItemGroup>\n"
	"  <ItemGroup>\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.Analyzers.15.0.743\\analyzers\\Microsoft.VisualStudio.ProjectSystem.Analyzers.dll\" />\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.Threading.Analyzers.15.0.240\\analyzers\\cs\\Microsoft.VisualStudio.Threading.Analyzers.dll\" />\n"
	"  </ItemGroup>\n"
	"  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" />\n"
	"  <Import Project=\"$(VSToolsPath)\\VSSDK\\Microsoft.VsSDK.targets\" Condition=\"'$(VSToolsPath)' != ''\" />\n"
	"  <!-- TODO: This copies the build authoring to a well-known location so that on the machine this project builds on,\n"
	"       the projects created by the 3rd party consumer can open and build. But the real 3rd party consumer will not\n"
	"       have run this step so they won't be able to open their projects. \n"
	"       To ship, the project type author must create an MSI that places these files in a well-known location on the\n"
	"       customer machine and update the project template to point at that location.-->\n"
	"  <Target Name=\"AfterBuild\">\n"
	"    <ItemGroup>\n"
	"      <BuildSystemToCopy Include=\"BuildSystem\\DeployedBuildSystem\\**\\*\" />\n"
	"      <RulesToCopy Include=\"BuildSystem\\Rules\\**\\*\" />\n"
	"    </ItemGroup>\n"
	"    <Copy SourceFiles=\"@(BuildSystemToCopy)\" DestinationFiles=\"@(BuildSystemToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\n"
	"    <Copy SourceFiles=\"@(RulesToCopy)\" DestinationFiles=\"@(RulesToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\Rules\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\n"
	"  </Target>\n"
	"  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">\n"
	"    <PropertyGroup>\n"
	"      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>\n"
	"    </PropertyGroup>\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets'))\" />\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets'))\" />\n"
	"  </Target>\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" />\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" />\n"
	"</Project>"
};

}

#endif
