#ifndef VS_PROJECT_TYPE_DATA_H
#define VS_PROJECT_TYPE_DATA_H

namespace CP2
{

static const char* const kaszVSProjectData[] =
{
	"<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n"
	"<Project ToolsVersion=\"4.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n"
	"  <PropertyGroup>\r\n"
	"    <MinimumVisualStudioVersion>15.0</MinimumVisualStudioVersion>\r\n"
	"    <VisualStudioVersion Condition=\"'$(VisualStudioVersion)' == ''\">15.0</VisualStudioVersion>\r\n"
	"    <VSToolsPath Condition=\"'$(VSToolsPath)' == ''\">$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)</VSToolsPath>\r\n"
	"    <NuGetPackageImportStamp>\r\n"
	"    </NuGetPackageImportStamp>\r\n"
	"  </PropertyGroup>\r\n"
	"  <Import Project=\"$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props\" Condition=\"Exists('$(MSBuildExtensionsPath)\\$(MSBuildToolsVersion)\\Microsoft.Common.props')\" />\r\n"
	"  <PropertyGroup>\r\n"
	"    <Configuration Condition=\" '$(Configuration)' == '' \">Debug</Configuration>\r\n"
	"    <Platform Condition=\" '$(Platform)' == '' \">AnyCPU</Platform>\r\n"
	"    <ProductVersion>8.0.30703</ProductVersion>\r\n"
	"    <SchemaVersion>2.0</SchemaVersion>\r\n"
	"    <ProjectTypeGuids>{82b43b9b-a64c-4715-b499-d71e9ca2bd60};{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}</ProjectTypeGuids>\r\n"
	"    <ProjectGuid>{",
	// project guid
	"}</ProjectGuid>\r\n"
	"    <OutputType>Library</OutputType>\r\n"
	"    <AppDesignerFolder>Properties</AppDesignerFolder>\r\n"
	"    <RootNamespace>",
	// language name
	"</RootNamespace>\r\n"
	"    <AssemblyName>",
	// language name
	"</AssemblyName>\r\n"
	"    <TargetFrameworkVersion>v4.6</TargetFrameworkVersion>\r\n"
	"    <FileAlignment>512</FileAlignment>\r\n"
	"    <SignAssembly>true</SignAssembly>\r\n"
	"    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>\r\n"
	"    <StartAction>Program</StartAction>\r\n"
	"    <StartProgram>$(DevEnvDir)devenv.exe</StartProgram>\r\n"
	"    <StartArguments>/rootSuffix Exp</StartArguments>\r\n"
	"  </PropertyGroup>\r\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">\r\n"
	"    <DebugSymbols>true</DebugSymbols>\r\n"
	"    <DebugType>full</DebugType>\r\n"
	"    <Optimize>false</Optimize>\r\n"
	"    <OutputPath>bin\\Debug\\</OutputPath>\r\n"
	"    <DefineConstants>DEBUG;TRACE</DefineConstants>\r\n"
	"    <ErrorReport>prompt</ErrorReport>\r\n"
	"    <WarningLevel>4</WarningLevel>\r\n"
	"  </PropertyGroup>\r\n"
	"  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' \">\r\n"
	"    <DebugType>pdbonly</DebugType>\r\n"
	"    <Optimize>true</Optimize>\r\n"
	"    <OutputPath>bin\\Release\\</OutputPath>\r\n"
	"    <DefineConstants>TRACE</DefineConstants>\r\n"
	"    <ErrorReport>prompt</ErrorReport>\r\n"
	"    <WarningLevel>4</WarningLevel>\r\n"
	"  </PropertyGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Reference Include=\"EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"envdte100, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"envdte90, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build.Framework\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Framework.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.Build.Utilities.Core\">\r\n"
	"      <HintPath>$(MSBuildBinPath)\\Microsoft.Build.Utilities.Core.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.CSharp\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ComponentModelHost\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Composition.Configuration, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Composition.15.0.71\\lib\\net45\\Microsoft.VisualStudio.Composition.Configuration.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Designer.Interfaces, Version=1.0.5000.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.OLE.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.Interop, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.Interop.dll</HintPath>\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.ProjectSystem.VS, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.15.0.743\\lib\\net46\\Microsoft.VisualStudio.ProjectSystem.VS.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.8.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.9.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.10.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.11.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.0\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.12.1.DesignTime\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Interop.14.0.DesignTime\">\r\n"
	"      <EmbedInteropTypes>True</EmbedInteropTypes>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.Framework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <SpecificVersion>True</SpecificVersion>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Shell.15.0\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.TextManager.Interop, Version=7.1.40304.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Threading, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Threading.15.0.240\\lib\\net45\\Microsoft.VisualStudio.Threading.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"Microsoft.VisualStudio.Validation, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.VisualStudio.Validation.15.0.82\\lib\\net45\\Microsoft.VisualStudio.Validation.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"PresentationCore\" />\r\n"
	"    <Reference Include=\"PresentationFramework\" />\r\n"
	"    <Reference Include=\"System\" />\r\n"
	"    <Reference Include=\"System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\System.Collections.Immutable.1.3.1\\lib\\portable-net45+win8+wp8+wpa81\\System.Collections.Immutable.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.ComponentModel.Composition\" />\r\n"
	"    <Reference Include=\"System.Composition.AttributedModel, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.AttributedModel.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Convention, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Convention.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Hosting, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Hosting.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.Runtime, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.Runtime.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Composition.TypedParts, Version=1.0.30.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Composition.1.0.30\\lib\\portable-net45+win8+wp8+wpa81\\System.Composition.TypedParts.dll</HintPath>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Core\" />\r\n"
	"    <Reference Include=\"System.Data\" />\r\n"
	"    <Reference Include=\"System.Design\" />\r\n"
	"    <Reference Include=\"System.Drawing\" />\r\n"
	"    <Reference Include=\"System.Threading.Tasks.Dataflow, Version=4.5.24.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL\">\r\n"
	"      <HintPath>..\\..\\packages\\Microsoft.Tpl.Dataflow.4.5.24\\lib\\portable-net45+win8+wpa81\\System.Threading.Tasks.Dataflow.dll</HintPath>\r\n"
	"      <Private>True</Private>\r\n"
	"    </Reference>\r\n"
	"    <Reference Include=\"System.Windows.Forms\" />\r\n"
	"    <Reference Include=\"System.Xaml\" />\r\n"
	"    <Reference Include=\"System.Xml\" />\r\n"
	"    <Reference Include=\"System.Xml.Linq\" />\r\n"
	"    <Reference Include=\"VSLangProj, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />\r\n"
	"    <Reference Include=\"WindowsBase\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <ProjectReference Include=\"..\\ProjectTemplate\\",
	// language name
	".ProjectTemplate.csproj\">\r\n"
	"      <Project>{",
	// project template project guid
	"}</Project>\r\n"
	"      <Name>",
	// language name
	".ProjectTemplate</Name>\r\n"
	"      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>\r\n"
	"      <IncludeOutputGroupsInVSIX>TemplateProjectOutputGroup%3b</IncludeOutputGroupsInVSIX>\r\n"
	"      <VSIXSubPath>ProjectTemplates</VSIXSubPath>\r\n"
	"    </ProjectReference>\r\n"
	"  </ItemGroup>\r\n"
	"  <!-- \r\n"
	"  Resources for our new project system\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <EmbeddedResource Include=\"Resources.resx\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </EmbeddedResource>\r\n"
	"    <EmbeddedResource Include=\"VSPackage.resx\">\r\n"
	"      <MergeWithCTO>true</MergeWithCTO>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </EmbeddedResource>\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Compile Include=\"MyConfiguredProject.cs\" />\r\n"
	"    <Compile Include=\"MyUnconfiguredProject.cs\" />\r\n"
	"    <Compile Include=\"ProjectProperties.cs\" />\r\n"
	"    <Compile Include=\"ScriptDebuggerLaunchProvider.cs\" />\r\n"
	"    <Compile Include=\"VsPackage.cs\" />\r\n"
	"    <Compile Include=\"Properties\\AssemblyInfo.cs\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"app.config\" />\r\n"
	"    <None Include=\"packages.config\" />\r\n"
	"    <None Include=\"source.extension.vsixmanifest\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <None Include=\"Key.snk\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <!-- \r\n"
	"  These are the parts of the custom project system which will be deployed as part of the \r\n"
	"  final implementation, and provide the basic processing for handling rules in CPS.\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".props\" />\r\n"
	"    <None Include=\"BuildSystem\\DeployedBuildSystem\\",
	// language name
	".targets\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <!--\r\n"
	"  The XAML files provide buth compile-time implementations for CPS rules as well as\r\n"
	"  runtime information for property pages.  They will also be deployed as part of the\r\n"
	"  final package.\r\n"
	"  -->\r\n"
	"  <ItemGroup>\r\n"
	"    <None Include=\"BuildSystem\\Rules\\ProjectItemsSchema.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <None Include=\"BuildSystem\\Rules\\script.browseobject.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </None>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general_file.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\folder.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\none.xaml\">\r\n"
	"      <RuleInjection>None</RuleInjection>\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\scc.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\debugger_general.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\script.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\general.browseobject.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"    <XamlPropertyRule Include=\"BuildSystem\\Rules\\ScriptDebugger.xaml\">\r\n"
	"      <SubType>Designer</SubType>\r\n"
	"    </XamlPropertyRule>\r\n"
	"  </ItemGroup>\r\n"
	"  <ItemGroup>\r\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.Analyzers.15.0.743\\analyzers\\Microsoft.VisualStudio.ProjectSystem.Analyzers.dll\" />\r\n"
	"    <Analyzer Include=\"..\\..\\packages\\Microsoft.VisualStudio.Threading.Analyzers.15.0.240\\analyzers\\cs\\Microsoft.VisualStudio.Threading.Analyzers.dll\" />\r\n"
	"  </ItemGroup>\r\n"
	"  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" />\r\n"
	"  <Import Project=\"$(VSToolsPath)\\VSSDK\\Microsoft.VsSDK.targets\" Condition=\"'$(VSToolsPath)' != ''\" />\r\n"
	"  <!-- TODO: This copies the build authoring to a well-known location so that on the machine this project builds on,\r\n"
	"       the projects created by the 3rd party consumer can open and build. But the real 3rd party consumer will not\r\n"
	"       have run this step so they won't be able to open their projects. \r\n"
	"       To ship, the project type author must create an MSI that places these files in a well-known location on the\r\n"
	"       customer machine and update the project template to point at that location.-->\r\n"
	"  <Target Name=\"AfterBuild\">\r\n"
	"    <ItemGroup>\r\n"
	"      <BuildSystemToCopy Include=\"BuildSystem\\DeployedBuildSystem\\**\\*\" />\r\n"
	"      <RulesToCopy Include=\"BuildSystem\\Rules\\**\\*\" />\r\n"
	"    </ItemGroup>\r\n"
	"    <Copy SourceFiles=\"@(BuildSystemToCopy)\" DestinationFiles=\"@(BuildSystemToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\r\n"
	"    <Copy SourceFiles=\"@(RulesToCopy)\" DestinationFiles=\"@(RulesToCopy->'$(LocalAppData)\\CustomProjectSystems\\",
	// language name
	"\\Rules\\%(RecursiveDir)%(FileName)%(Extension)')\" SkipUnchangedFiles=\"true\" />\r\n"
	"  </Target>\r\n"
	"  <Target Name=\"EnsureNuGetPackageBuildImports\" BeforeTargets=\"PrepareForBuild\">\r\n"
	"    <PropertyGroup>\r\n"
	"      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>\r\n"
	"    </PropertyGroup>\r\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets'))\" />\r\n"
	"    <Error Condition=\"!Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" Text=\"$([System.String]::Format('$(ErrorText)', '..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets'))\" />\r\n"
	"  </Target>\r\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.SDK.VsixSuppression.14.1.32\\build\\Microsoft.VisualStudio.SDK.VsixSuppression.targets')\" />\r\n"
	"  <Import Project=\"..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets\" Condition=\"Exists('..\\..\\packages\\Microsoft.VisualStudio.ProjectSystem.SDK.Tools.15.0.743\\build\\Microsoft.VisualStudio.ProjectSystem.Sdk.Tools.targets')\" />\r\n"
	"</Project>"
};

}

#endif
